### ISSUE TITLE
can u pls update to oc0.6.3?

### ISSUE THREAD

**Issue by shanezhan** [shinrai2/ASUS-TUF-GAMING-B460M-PLUS-RX5600XT-Hackintosh-Opencore#1]
hello,
my motherboad is ASUS-TUF-GAMING-B460M-PLUS-wifi +RX5500xt,
i try to install big sur 11.0.1 with this efi ,working fine on the begin,but when i restart my computer,the screen is black.
i have no idea now T_T

**Comment by shinrai2** [comment]
@shanezhan

I am glad to discuss the problem w/ u, but I need more info.
How did you restart your pc? Use the mac's menu or your device's restart btn?
And what is the status of the device after restarting, is u fan spinning? Is oc's menu displayed?
I don't have any clues about the problem you described.

**Comment by shanezhan** [comment]
@shinrai2 hihi
thanks for your kindly reply,
everything is ok when i install big sur ,but when i reboot the computer ,Using the mac's menu ,
it will show the oc menu,and choose the osx for booting, everything will be ok at begin,but at last the screen do not display anything,it show no signal ，but i try to type the psw ,the hard disc light is shining.so i think system is trunning on success,but display signal is not output.i don't know why.
and now i try to insall catlina v10.15.7,everything is ok now....
so maybe it's the problem of big sur?

**Comment by shinrai2** [comment]
@shanezhan 

sounds like a kernel panic has occurred.
if you want to figure out what caused the problem, i suggest adding the following params to the boot args, and record the log output on the screen when restarting. 
`keepsyms=1 -v -no_compat_check`
usu the screen will be black again when output is over, so i will take it with my cam. i hope you have a better way :p
