### ISSUE TITLE
May I plz ask u to add support for UHD630？

### ISSUE THREAD

**Issue by Oniokey** [shinrai2/ASUS-TUF-GAMING-B460M-PLUS-RX5600XT-Hackintosh-Opencore#2]
I have built up a pc without the dGPU because of the high price.So I use the iGPU UHD630 now.For this reason above,maybe u could add support for UHD630.Thx a lot.

**Comment by shinrai2** [comment]
@TodayNow Iwill try it ........ in next few days. Busy@ work :(
